### ISSUE TITLE
entry_tranメソッドはSite APIに存在しないがWikiに説明があります

### ISSUE THREAD

**Issue by shingo-nakanishi** [t-k/gmo-payment-ruby#11]
- [Site API · t-k/gmo-payment-ruby Wiki](https://github.com/t-k/gmo-payment-ruby/wiki/Site-API#2121%E5%8F%96%E5%BC%95%E7%99%BB%E9%8C%B2entrytran)

に`2.1.2.1.取引登録(EntryTran)`の解説がありますが、
https://github.com/t-k/gmo-payment-ruby/blob/master/lib/gmo/site_api.rb
を確認すると`entry_tran`はありません。

Shop API
- https://github.com/t-k/gmo-payment-ruby/blob/master/lib/gmo/shop_api.rb
- [Shop API · t-k/gmo-payment-ruby Wiki](https://github.com/t-k/gmo-payment-ruby/wiki/Shop-API#2121%E5%8F%96%E5%BC%95%E7%99%BB%E9%8C%B2entrytran)

には存在しますので、単純に

Site APIのWikiの説明から削除かと思われます。

**Comment by jiikko** [comment]
issueありがとうございます。wikiはすでに修正済みのようなのでクローズします。
