### ISSUE TITLE
クレジットカード決済サービス　調査

### ISSUE THREAD

**Issue by olllive** [t-k/gmo-payment-ruby#12]
## ペイジェント加盟店サポートページ
　http://www.paygent.co.jp/merchant/
　ID： paygent   PASSWORD： payment

## GMO
https://github.com/t-k/gmo-payment-ruby

**Comment by takuma-saito** [comment]
@t-k I'm sorry our director creating unreated issues. 
she wanted to create this issue in our repository, but she did it in this repository by mistake. 
I though that maybe you were offended, Please not feel bad...
We can't delete the issue, so immediately closed it. 
I'm so sorry about it.
