### ISSUE TITLE
半角カナをレスポンスにあった時に文字化けする

### ISSUE THREAD

**Issue by um-zagaa** [t-k/gmo-payment-ruby#33]
## 問題
GMOのAPIレスポンスに半角カナの文字列を含む場合、文字化けするケースがあります。

## 実現方法
APIからの文字列:   ｼﾞｰｴﾑｵｰｱｵｿﾞﾗﾈｯﾄ
GMOのAPIから取得した文字列: 郷骸竹

## 修正提案
https://github.com/t-k/gmo-payment-ruby/blob/master/lib/gmo.rb#L43
lib/gmo.rbの中にエンディングしてるコードを変更する。

変更前のコード:
`body = response = Hash[response.map { |k,v| [k, NKF.nkf('-w',v)] }]`
変更後のコード:
`body = response = Hash[response.map { |k,v| [k, v.force_encoding('Shift_JIS').encode('UTF-8')] }]`

**Comment by jiikko** [comment]
@um-zagaa 
Thank you for to create a issue.
I will try to check.

**Comment by jiikko** [comment]
@um-zagaa 
i had not reproduced it with my env.

ruby 2.4.4p296

```ruby
exec_params = {
  [...]
  client_field_1: 'ｼﾞｰｴﾑｵｰｱｵｿﾞﾗﾈｯﾄ',
  [...]
}
irb(main):301:0> shop_api.exec_tran_pay_easy(exec_params)
irb(main):305:0> shop_api.search_trade_multi(search_params).slice('ClientField1')
=> {"ClientField1"=>"ジーエムオーアオゾラネット"}
```

```ruby
irb(main):017:0* NKF.nkf('-w', 'ｼﾞｰｴﾑｵｰｱｵｿﾞﾗﾈｯﾄ')
=> "ジーエムオーアオゾラネット"
```

I seem to need anything else to reproduce.
Could you make a reproducing code or a pull request?

**Comment by um-zagaa** [comment]
@jiikko 
Thank you for your support

my env:
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
Rails 6.0.0

I am using virtual payment method.

When i using my app without override api method, result is bellow.
![image](https://user-images.githubusercontent.com/32889024/87895039-01e62380-ca77-11ea-8072-e327ec93dfad.png)

When i override api method with encoding, result is bellow.
![image](https://user-images.githubusercontent.com/32889024/87895445-0eb74700-ca78-11ea-8002-5e9d4bad616b.png)

When i use encoding directly, seems half sized kana become 2 byte kana but still readable.
![image](https://user-images.githubusercontent.com/32889024/87895533-445c3000-ca78-11ea-96dc-3e37c90e785b.png)

maybe it is not encoding issue, but virtual payment api param issue?
![image](https://user-images.githubusercontent.com/32889024/87895588-69e93980-ca78-11ea-980f-0c47ea368f64.png)

> Could you make a reproducing code or a pull request?
> I seem to need anything else to reproduce.

My project is cannot be exposed in public. sorry i can only share my information part that can be exposed in public. if anything else needed let me know. :pray:

**Comment by jiikko** [comment]
Shift_JISで書いた`ｶｿｳｼﾃﾝ`をEUC-JPで読み込むと`郷骸竹`として表示されました。

```shell
vim -c ":e ++enc=shift_jis" x.txt  # write `ｶｿｳｼﾃﾝ`
vim -c ":e ++enc=euc-jp" x.txt  # printed `郷骸竹`
```

@um-zagaa さんの環境で起きているこの文字化けは、エディタが行っている文字コード自動判別みたいな機能の誤判定のように見えます。
エディタの文字コードをUTF-8にする、など試してみてください。

もし、レスポンスに半角カナが含まれている場合にどの環境でも文字化けするのであれば、`#exec_tran_cvs`あたりのメソッドでも再現するはずですので、リグレッションテストつきのプルリクエストを送ってくれるとうれしいです。
本リポジトリで既に使っている、vcrというgemを使うと外部APIの入出力を記録してテストの入力として使うことができます。なので、プロダクトコードなしで再現コードを作れるはずです。

**Comment by um-zagaa** [comment]
@jiikko 
ご回答ありがとうございます。
こちらの文字化けは開発中のプロジェクトではどんな環境でも再現していました。
そのため、こちらでプロジェクトでエンコーディン部分を変更して利用しました。
こちらの情報を共有は不可のなので、このIssueはクロースします。

ご協力ありがとうございました。
